# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='join', max_length=120),
            preserve_default=False,
        ),
    ]
