# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateField(blank=True, default=b'2019-02-28 12:37:59', null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
