# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 04:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190228_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 28, 12, 58, 1, 738000), null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
