# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190228_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
