# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190228_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSitesClassificationLeval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u5206\u7c7b\u540d')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.WebSitesClassificationLeval')),
            ],
            options={
                'db_table': 'WebSitesClassificationLeval',
                'verbose_name_plural': '\u7f51\u7ad9\u5206\u7c7b',
            },
        ),
    ]
