# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ManyToManyField(to='app01.Teachers'),
        ),
    ]
